.TH "tinyscheme" "1" "" ""
.SH NAME
.PP
tinyscheme \(em a tiny Scheme implementation
.SH SYNOPSIS
.PP
\fBtinyscheme\fP [ -? ] 
.br
\fBtinyscheme\fP \fIfile\fP [ \fIfile2\fP .\|.\|. ] 
.br
\fBtinyscheme\fP -1 \fIfile\fP [ \fIargs\fP .\|.\|. ]
.SH OPTIONS
.PP
Without options, \fBtinyscheme\fP enters a read-eval-print loop.
.RS 3
.TP
\&\fC-?\fP
Show a usage message.
.TP
\&\fC-1\fP
Run a script with arguments.
.RE
.SH AUTHOR
.PP
This manual page was written for the Debian distribution by Panu Kalliokoski.
